### ISSUE TITLE
Php.ini file not found

### ISSUE THREAD

**Issue by seweissman** [Jahia/scriptlanguages#2]
When I try to tell quercus how to find my php.ini file (in src/main/resources/WEB-INF/php.ini) it doesn't recognize the path. Both

```
 <bean id="quercusServlet" class="com.caucho.quercus.servlet.QuercusServlet">
    <property name="iniFile" value="/WEB-INF/php.ini"/>
 </bean>
```

and

```
 <bean id="httpServiceListener" class="org.jahia.services.render.scripting.quercus.HttpServiceListener">
    <property name="alias" value="/scripts/php" />
    <property name="servlet" ref="quercusServlet" />
    <property name="initParameters">
        <props>
            <!--prop key="license-directory">WEB-INF/licenses</prop-->
            <prop key="ini-file">/WEB-INF/php.ini</prop>
        </props>
    </property>
 </bean>
```

(with or without leading slash) don't work. Looking into the Quercus source code, it uses ServletContext.getRealPath, which doesn't return anything, or QuercusContext.getPwd(), which returns "<digital-factory-install-dir>/tomcat/bin." I don't know if this is something that can be fixed by registering the servlet with the proper context, or if this is something that can only be handled within Quercus.

I'm sure there are many reasons to want to include a php.ini file, but the particular one that interests me is that Quercus uses parameters from php.ini to configure PDO JDBC drivers outside of the default set it recognizes. (See http://forum.caucho.com/showthread.php?p=35403). The only other way to tell Quercus how to find a database is to use JNDI, which also appears to be incompatible with OSGI. Since Quercus does not implement all of the different extensions out there for different DBs, this is really the only option I can see if you need to access a database in your PHP code.

**Comment by sergehuber** [comment]
Ok I've made it possible to use a php.ini file. I put an empty file in META-INF/quercus/php.ini

and now it is also possible to set the class path location from the Spring configuration file as in the following example : 

```
<bean id="quercusScriptEngineFactory" class="org.jahia.services.render.scripting.quercus.JahiaQuercusScriptEngineFactory">
    <property name="iniFileClassPathLocation" value="META-INF/quercus/php.ini" />
</bean>
```
